services:
  - type: web
    name: wireguard-server
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: PUID
        value: "1000"
      - key: PGID
        value: "1000"
      - key: TZ
        value: Europe/Moscow
