services:
  - type: web
    name: brook-vpn
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: TZ
        value: Europe/Moscow
